import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Image from "next/image";
import logo from "../public/vercel.svg";
import { createClient } from "contentful";
import Hero from "../components/Hero";
import Container from "../components/Container/Container";

import { documentToReactComponents } from "@contentful/rich-text-react-renderer";
import ServiceCard from "../components/ServiceCard";
import Service from "../components/Service/Service";

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
  });

  const res = await client.getEntries({ content_type: "service" });

  return {
    props: {
      services: res.items,
    },
  };
}

export default function Home({ services }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Arcane</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container>
          <Hero />
          {/* <div id="services" className={styles.servicesContainer}>
            <h1 className={styles.services__heading}>Services</h1>
            <div className={styles.services__section}>
              <ServiceCard />
            </div>
          </div> */}
          <Service services={services} />
        </Container>

        {/* <div className={styles.services__section}>
            <div className={styles.service}>
              <Image src={logo} className={styles.services__icon} alt="logo" />

              <h4 className={styles.service__heading}>Urban Developement</h4>
            </div>
            <div className={styles.service}>
              <Image src={logo} className={styles.services__icon} alt="logo" />

              <h4 className={styles.service__heading}>Bridges</h4>
            </div>
            <div className={styles.service}>
              <Image src={logo} className={styles.services__icon} alt="logo" />

              <h4 className={styles.service__heading}>Railways & Metros</h4>
            </div>
            <div className={styles.service}>
              <Image src={logo} className={styles.services__icon} alt="logo" />

              <h4 className={styles.service__heading}>Environment & Social</h4>
            </div>
            <div className={styles.service}>
              <Image src={logo} className={styles.services__icon} alt="logo" />

              <h4 className={styles.service__heading}>Apartments</h4>
            </div> */}
        {/* </div> */}
      </div>
    </>
  );
}
