import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Image from "next/image";
import logo from "../public/vercel.svg";
import { createClient } from "contentful";
import Hero from "../components/Hero/Hero";
import Container from "../components/Container/Container";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";
import Service from "../components/Service/Service";

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
  });

  const res = await client.getEntries({ content_type: "service" });

  return {
    props: {
      services: res.items,
    },
  };
}

export default function Home({ services }) {
  console.log(services);
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Arcane</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container>
          <Hero />
          <Service services={services} />
        </Container>
      </div>
    </>
  );
}
